name: Check for broken links on site

on:
  workflow_run:
    workflows:
      - Deploy site
    types:
      - completed

permissions:
  contents: read

jobs:
  check-links-on-site:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check local links
        uses: lycheeverse/lychee-action@v2.1.0
        with:
          fail: true
          args: --offline --verbose --no-progress "docs/**/*.html"
