name: Prettier code formatter

on:
  pull_request:
    branches:
      - main
    paths:
      - "docs/**"
      - "README.md"
      - ".github/workflows/deploy.yml"
      - ".github/workflows/broken-links-site.yml"
      - ".github/workflows/prettier.yml"
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "README.md"
      - ".github/workflows/deploy.yml"
      - ".github/workflows/broken-links-site.yml"
      - ".github/workflows/prettier.yml"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Check production files
        run: >-
          npx prettier
          docs/index.html
          docs/styles.css
          .github/workflows/deploy.yml
          .github/workflows/broken-links-site.yml
          .github/workflows/prettier.yml
          README.md
          --check
